all:
  hosts:
    rocky-test-02:
      ansible_host: 192.168.0.114
      ansible_user: cwalls
    docker-test:
      ansible_host: 192.168.0.175
      ansible_user: dracula
    pihole:
      ansible_host: 192.168.0.197
      ansible_user: dracula
    unifi:
      ansible_host: 192.168.0.181
      ansible_user: dracula
    docker-host:
      ansible_host: 192.168.0.184
      ansible_user: dracula
    nginx_proxy_manager:
      ansible_host: 192.168.0.33
      ansible_user: dracula
