- name: Install qemu
  hosts: tf-test-clone
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.package:
        update_cache: yes
    - name: Install qemu guest agent
      ansible.builtin.package:
        name: qemu-guest-agent
        state: present

    - name: Reboot
      ansible.builtin.reboot:
      
