- name: Install Apache
  hosts: all
  become: true
  tasks:
    - name: Install httpd on Rocky
      ansible.builtin.package:
        name: httpd
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Install Apache on Ubuntu
      ansible.builtin.package:
        name: apache2
        state: absent
      when: ansible_os_family == "Debian"
